/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package paquetePrincipal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class ventanaPrincipal extends javax.swing.JFrame {
Connection conexion;
java.sql.Statement sentencia;
    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        prepararBaseDatos();
    }
    final void prepararBaseDatos(){
        try {
            String controlador="com.mysql.jdbc.Driver";
            Class.forName(controlador).newInstance();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error al Cargar el controlador "+e);
        }
         
        try {
            String DSN ="jdbc:mysql://localhost/mamepsa";
            String user="root";
            String pass="";
            conexion=DriverManager.getConnection(DSN, user, pass);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error al conectar la base de datos "+e);
        }
        
        try {
             sentencia= conexion.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al crear el Objeto"+ e);
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerDatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPanel = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        btnIgual = new javax.swing.JButton();
        btnMayor = new javax.swing.JButton();
        btnMenor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnNombreIgual = new javax.swing.JButton();
        btnContiene = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnVerDatos.setText("Ver Datos Trabajador");
        btnVerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDatosActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtPanel);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Sueldo");

        btnIgual.setText("Igual");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnMayor.setText("Mayor que");
        btnMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorActionPerformed(evt);
            }
        });

        btnMenor.setText("Menor que");
        btnMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        btnNombreIgual.setText("Igual a");
        btnNombreIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreIgualActionPerformed(evt);
            }
        });

        btnContiene.setText("Contiene a ");
        btnContiene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContieneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVerDatos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIgual)
                                .addGap(18, 18, 18)
                                .addComponent(btnMayor)
                                .addGap(18, 18, 18)
                                .addComponent(btnMenor))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNombreIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnVerDatos)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIgual)
                    .addComponent(btnMayor)
                    .addComponent(btnMenor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNombreIgual)
                    .addComponent(btnContiene))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDatosActionPerformed
        // TODO add your handling code here:
        String info="";
        String cadnombre;
        String cadapell;
        String cadsueldo;
        String cadfecha;
        try {
            ResultSet r = sentencia.executeQuery("SELECT * FROM trabajadores ORDER BY sueldo");
            r.beforeFirst();
            while ( r.next()) {                
               cadnombre=r.getString("nombre");
               cadapell=r.getString("apellido");
               cadsueldo=r.getString("sueldo");
               cadsueldo=cadsueldo.replace(".", ",");
               cadfecha=r.getString("fecha");
               cadfecha=cadfecha.substring(8,10)+"/"+cadfecha.substring(5,7)+"/"+cadfecha.substring(0,4);
               info=info+cadnombre+" "+cadapell+"----"+cadsueldo+"----"+cadfecha+"\n";
            }
            txtPanel.setText("");
            txtPanel.setText(info);
                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al consultar tabla trabajadores "+e);
        }
    }//GEN-LAST:event_btnVerDatosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            conexion.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cerrar la conexio \n"+e);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
        String info="";
        String cadnombre;
        String cadapell;
        String cadsueldo;
        String cadfecha;
        try {
            ResultSet r = sentencia.executeQuery("SELECT * FROM trabajadores WHERE sueldo =" +txtSueldo.getText());
            r.beforeFirst();
            while ( r.next()) {                
               cadnombre=r.getString("nombre");
               cadapell=r.getString("apellido");
               cadsueldo=r.getString("sueldo");
               cadsueldo=cadsueldo.replace(".", ",");
               cadfecha=r.getString("fecha");
               cadfecha=cadfecha.substring(8,10)+"/"+cadfecha.substring(5,7)+"/"+cadfecha.substring(0,4);
               info=info+cadnombre+" "+cadapell+"----"+cadsueldo+"----"+cadfecha+"\n";
            }
            txtPanel.setText("");
            txtPanel.setText(info);
                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al consultar tabla trabajadores "+e);
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorActionPerformed
        // TODO add your handling code here:
        String info="";
        String cadnombre;
        String cadapell;
        String cadsueldo;
        String cadfecha;
        try {
            ResultSet r = sentencia.executeQuery("SELECT * FROM trabajadores WHERE sueldo >" +txtSueldo.getText());
            r.beforeFirst();
            while ( r.next()) {                
               cadnombre=r.getString("nombre");
               cadapell=r.getString("apellido");
               cadsueldo=r.getString("sueldo");
               cadsueldo=cadsueldo.replace(".", ",");
               cadfecha=r.getString("fecha");
               cadfecha=cadfecha.substring(8,10)+"/"+cadfecha.substring(5,7)+"/"+cadfecha.substring(0,4);
               info=info+cadnombre+" "+cadapell+"----"+cadsueldo+"----"+cadfecha+"\n";
            }
            txtPanel.setText("");
            txtPanel.setText(info);
                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al consultar tabla trabajadores "+e);
        }
    }//GEN-LAST:event_btnMayorActionPerformed

    private void btnMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorActionPerformed
        // TODO add your handling code here:
        String info="";
        String cadnombre;
        String cadapell;
        String cadsueldo;
        String cadfecha;
        try {
            ResultSet r = sentencia.executeQuery("SELECT * FROM trabajadores WHERE sueldo <"+ txtSueldo.getText());
            r.beforeFirst();
            while ( r.next()) {                
               cadnombre=r.getString("nombre");
               cadapell=r.getString("apellido");
               cadsueldo=r.getString("sueldo");
               cadsueldo=cadsueldo.replace(".", ",");
               cadfecha=r.getString("fecha");
               cadfecha=cadfecha.substring(8,10)+"/"+cadfecha.substring(5,7)+"/"+cadfecha.substring(0,4);
               info=info+cadnombre+" "+cadapell+"----"+cadsueldo+"----"+cadfecha+"\n";
            }
            txtPanel.setText("");
            txtPanel.setText(info);
                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al consultar tabla trabajadores "+e);
        }
    }//GEN-LAST:event_btnMenorActionPerformed

    private void btnNombreIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreIgualActionPerformed
        // TODO add your handling code here:
        String info="";
        String cadnombre;
        String cadapell;
        String cadsueldo;
        String cadfecha;
        try {
            String consulta;
            consulta= "SELECT * FROM trabajadores WHERE nombre = '"+txtNombre.getText()+"' ";
            ResultSet r = sentencia.executeQuery(consulta);
            r.beforeFirst();
            while ( r.next()) {                
               cadnombre=r.getString("nombre");
               cadapell=r.getString("apellido");
               cadsueldo=r.getString("sueldo");
               cadsueldo=cadsueldo.replace(".", ",");
               cadfecha=r.getString("fecha");
               cadfecha=cadfecha.substring(8,10)+"/"+cadfecha.substring(5,7)+"/"+cadfecha.substring(0,4);
               info=info+cadnombre+" "+cadapell+"----"+cadsueldo+"----"+cadfecha+"\n";
            }
            txtPanel.setText("");
            txtPanel.setText(info);
                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al consultar tabla trabajadores "+e);
        }
    }//GEN-LAST:event_btnNombreIgualActionPerformed

    private void btnContieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContieneActionPerformed
        // TODO add your handling code here:
        String info="";
        String cadnombre;
        String cadapell;
        String cadsueldo;
        String cadfecha;
        try {
            String consulta;
            consulta= "SELECT * FROM trabajadores WHERE nombre LIKE '%"+txtNombre.getText()+"%'";
            ResultSet r = sentencia.executeQuery(consulta);
            r.beforeFirst();
            while ( r.next()) {                
               cadnombre=r.getString("nombre");
               cadapell=r.getString("apellido");
               cadsueldo=r.getString("sueldo");
               cadsueldo=cadsueldo.replace(".", ",");
               cadfecha=r.getString("fecha");
               cadfecha=cadfecha.substring(8,10)+"/"+cadfecha.substring(5,7)+"/"+cadfecha.substring(0,4);
               info=info+cadnombre+" "+cadapell+"----"+cadsueldo+"----"+cadfecha+"\n";
            }
            txtPanel.setText("");
            txtPanel.setText(info);
                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al consultar tabla trabajadores "+e);
        }
    }//GEN-LAST:event_btnContieneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContiene;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMayor;
    private javax.swing.JButton btnMenor;
    private javax.swing.JButton btnNombreIgual;
    private javax.swing.JButton btnVerDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextPane txtPanel;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
