/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app22;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jose
 */
public class Ventana extends javax.swing.JFrame {
    JLabel lblNum1;
    JLabel lblNum2;
    JTextField txtNum1;
    JTextField txtNum2;
    JButton btnSumar;
    JButton btnRestar;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        CreacionVentana();
    }
    public void CreacionVentana(){
        this.setTitle("Programar Operacion");
        this.setSize(500, 300);
        this.setLocation(100, 100);
        
        lblNum1 = new JLabel();
        lblNum1.setText("Numero 1: ");
        lblNum1.setBounds(10,10,100,20);
        this.getContentPane().add(lblNum1);
        
        lblNum2 = new JLabel();
        lblNum2.setText("Numero 2: ");
        lblNum2.setBounds(10, 70, 100, 20);
        this.getContentPane().add(lblNum2);
        
        txtNum1 = new JTextField();
        txtNum1.setText("0");
        txtNum1.setBounds(125, 10, 135, 25);
        this.getContentPane().add(txtNum1);
        
        txtNum2 = new JTextField();
        txtNum2.setText("0");
        txtNum2.setBounds(125,70,135,25);
        this.getContentPane().add(txtNum2);
        
        btnSumar = new JButton();
        btnSumar.setText("Sumar");
        btnSumar.setBounds(10, 130, 100, 27);
        this.getContentPane().add(btnSumar);
        
        btnRestar = new JButton();
        btnRestar.setText("Restar");
        btnRestar.setBounds(160, 130, 100, 27);
        this.getContentPane().add(btnRestar);
        
        btnSumar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                btnSumarActionPerformed(e);
            }
        });
        
        btnRestar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                btnRestarActionPerformed(e);
            }
        });
        
    }
    public void btnSumarActionPerformed(ActionEvent evt){
            double a,b,s;
            a = Double.parseDouble(txtNum1.getText());
            b = Double.parseDouble(txtNum2.getText());
            s = a+b;
            JOptionPane.showMessageDialog(null, "La Suma Es: "+s);
        }
    
    public void btnRestarActionPerformed(ActionEvent evt){
            double a,b,s;
            a = Double.parseDouble(txtNum1.getText());
            b = Double.parseDouble(txtNum2.getText());
            s = a-b;
            JOptionPane.showMessageDialog(null, "La Resta Es: "+s);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
