/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package paquetePrincipal;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Oxxi
 */
public class pantallaPrincipal extends javax.swing.JFrame {
    Connection conn = null;
    /**
     * Creates new form pantallaPrincipal
     */
    public pantallaPrincipal() {
        initComponents();
        this.setTitle("Simple CRUD");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        conn = ConexionDB.getConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuEdita = new javax.swing.JMenu();
        itemTrabajadores = new javax.swing.JMenuItem();
        menuCon = new javax.swing.JMenu();
        itemConexion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuInicio.setText("Inicio");
        menuBar.add(menuInicio);

        menuEdita.setText("Editar");

        itemTrabajadores.setText("Editar Trabajadores");
        menuEdita.add(itemTrabajadores);

        menuBar.add(menuEdita);

        menuCon.setText("Conexion");

        itemConexion.setText("Probar Conexion");
        itemConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConexionActionPerformed(evt);
            }
        });
        menuCon.add(itemConexion);

        menuBar.add(menuCon);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConexionActionPerformed
        if (conn!=null) {
            JOptionPane.showMessageDialog(null, "Conexion Establecida :)");
        }
    }//GEN-LAST:event_itemConexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new pantallaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemConexion;
    private javax.swing.JMenuItem itemTrabajadores;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCon;
    private javax.swing.JMenu menuEdita;
    private javax.swing.JMenu menuInicio;
    // End of variables declaration//GEN-END:variables
}
