/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app24;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Jose
 */
public class VentanaPrincipal extends javax.swing.JFrame {
 JLabel lblTexto;
 JTextField txtDato;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        CreacionVentana();
    }
    public final void CreacionVentana(){
        this.setTitle("Programar Evento de Raton y teclado");
        this.setSize(400, 400);
        this.setLocation(100,100);
        
        lblTexto = new JLabel();
        lblTexto.setBounds(50,10,300,20);
        lblTexto.setText("------");
        this.getContentPane().add(lblTexto);
        
        txtDato = new JTextField();
        txtDato.setBounds(50, 40, 90, 27);
        txtDato.setText("");
        this.getContentPane().add(txtDato);
        
        ///listener mouse para lbltexto
        lblTexto.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e){
                lblTextoMouseEntered(e);
            }
            
            @Override
             public void mouseExited(MouseEvent e){
                lblTextoMouseExited(e);
            }
             
            @Override
             public void mousePressed(MouseEvent e){
                lblTextoMousePressed(e);
            }
            
            @Override
            public void mouseClicked(MouseEvent e){
                lblTextoMouseClicked(e);
            }
        });
        ///listener para txtDato
        txtDato.addKeyListener(new KeyAdapter() {
        
            @Override
         public void keyPressed(KeyEvent evt) {
		txtDatoKeyPressed(evt);
	}

            @Override
	public void keyReleased(KeyEvent evt) {
		txtDatoKeyReleased(evt);
	}

            @Override
	public void keyTyped(KeyEvent evt) {
		txtDatoKeyTyped(evt);
	}

        
        });
        
    }
    public void lblTextoMouseEntered(MouseEvent e){
        
    }
    public void lblTextoMouseExited(MouseEvent e){
        
    }
    public void lblTextoMousePressed(MouseEvent e){
        
    }
    public void lblTextoMouseClicked(MouseEvent e){
        
    }
    
    public void txtDatoKeyPressed(KeyEvent e){
        
    }
    public void txtDatoKeyReleased(KeyEvent e){
        
    }
    public void txtDatoKeyTyped(KeyEvent e){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
